### ISSUE TITLE
Non-existent VisualServer functions

### ISSUE THREAD

**Issue by SIsilicon** [Zylann/godot_hterrain_demo#2]
As soon as I try to play the scene, Godot complains about there not being an `instance_create` function in the `VisualServer` singleton. And as I looked through more of the code, I notice that there are other functions that `VisualServer` doesn't have. Was this ported from Godot 2?

**Comment by Zylann** [comment]
Some functions were not present in early 3.0. You need Godot 3.0.2 minimum. Later should work. If it doesn't, then it's a bug to fix.

If you can see the terrain in editor, then it should work ingame. If one works but not the other, then it's super weird and needs to be investigated.

**Comment by SIsilicon** [comment]
I *am* using 3.0.2 :/

**Comment by Zylann** [comment]
That's really weird... `instance_create` does exist in 3.0.2. you can see it in the docs, I've been using it for a long time now.
I cannot check myself until I get back home sunday evening.

**Comment by Zylann** [comment]
Also, please report those errors in the plugin repo, I don't think that's related to the demo.

**Comment by SIsilicon** [comment]
Ok thank you. I got the demo to work. Which led me to a different issue. See you in the repository. :)
