### ISSUE TITLE
Parse Error: Can't get index "x" on base "float".

### ISSUE THREAD

**Issue by jmdejong** [Zylann/godot_hterrain_demo#3]
When trying out this demo Godot can't load the bundled heightmap plugin because of a script error:

	SCRIPT ERROR: GDScript::reload: Parse Error: Can't get index "x" on base "float".
	At: res://addons/zylann.hterrain/hterrain.gd:361.
	ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
	At: modules/gdscript/gdscript.cpp:599.
	SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
	At: res://addons/zylann.hterrain/tools/plugin.gd:5.
	ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
	At: modules/gdscript/gdscript.cpp:599.
	SCRIPT ERROR: GDScript::reload: Parse Error: Can't get index "x" on base "float".
	At: res://addons/zylann.hterrain/hterrain.gd:361.
	ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
	At: modules/gdscript/gdscript.cpp:599.

When I install the newest version of the plugin from the asset lib the demo runs fine.

**Comment by Zylann** [comment]
Sorry I didnt take the time to maintain this demo, the plugin needs to be updated.

**Comment by Zylann** [comment]
I just updated the copy of the plugin in this repo.
